service: serverless-boilerplate

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, 'offline'}
  region: ${opt:region, 'us-east-1'}
  prismaEngine:
    offline: "node_modules/.prisma/client/*.node"
    staging: "node_modules/.prisma/client/libquery_engine-rhel*"
    prod: "node_modules/.prisma/client/libquery_engine-rhel*"

  esbuild:
    platform: "node"
    target: node16
    sourcemap: linked
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
    reloadHandler: true

provider:
  name: aws
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  runtime: nodejs16.x
  memorySize: 512
  timeout: 10
  logRetentionInDays: 90
  logs:
    httpApi: true
  httpApi:
    # metrics: true # Enable if you need
    cors: true

  # Add VPC configuration for RDS access
  vpc:
    securityGroupIds:
      - sg-xxxxxxxxxxxxxxxxx # Replace with your security group ID
    subnetIds:
      - subnet-xxxxxxxxxxxxxxxxx # Replace with your subnet IDs
      - subnet-xxxxxxxxxxxxxxxxx

  # Add IAM role statements for RDS access
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - rds-db:connect
            - rds:*
          Resource:
            - arn:aws:rds:${self:provider.region}:*:db:*
            - arn:aws:rds:${self:provider.region}:*:cluster:*
        - Effect: Allow
          Action:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
            - ec2:DescribeInstances
            - ec2:AttachNetworkInterface
          Resource: "*"

functions:
  app:
    handler: src/handler.handler
    # reservedConcurrency: 100
    events:
      - httpApi:
          path: "/{proxy+}"
          method: "*"

package:
  patterns:
    - "!**/*.test.ts"
    - ${self:custom.prismaEngine.${self:custom.stage}}
    - "node_modules/.prisma/client/schema.prisma"
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-offline
